import { getAttributeLabels } from './football-data.js';
const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const id = scope => String(scope).replace(/[^a-zA-Z0-9_-]/g, '_');
const point = (index, radius) => {
  const angle = -Math.PI / 2 + index * Math.PI / 3;
  return [190 + Math.cos(angle) * radius, 162 + Math.sin(angle) * radius];
};
const coords = (index, radius) => point(index, radius).map(n => n.toFixed(2)).join(',');
export function createRadarSvg(player, scope = 'radar') {
  const attributeLabels = getAttributeLabels(player);
  const prefix = id(scope);
  const levels = [25,50,75,99].map(level => `<polygon points="${attributeLabels.map((_,i) => coords(i,level/99*106)).join(' ')}" fill="none" stroke="#657d87" stroke-opacity=".45"/>`).join('');
  const axes = attributeLabels.map((_,i) => `<line x1="190" y1="162" x2="${point(i,106)[0]}" y2="${point(i,106)[1]}" stroke="#657d87" stroke-opacity=".45"/>`).join('');
  const labels = attributeLabels.map((label,i) => {
    const [x,y] = point(i,139); return `<text x="${x}" y="${y}" fill="#e5f5f5" text-anchor="middle" font-family="Arial,sans-serif" font-size="12">${escape(label)}<tspan x="${x}" dy="17" font-weight="bold">${player.attributes[i]}</tspan></text>`;
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 380 325" role="img" aria-labelledby="${prefix}-title ${prefix}-desc"><title id="${prefix}-title">Atributos ilustrativos de ${escape(player.name)}</title><desc id="${prefix}-desc">Escala de ejemplo de 0 a 99. ${escape(attributeLabels.map((label,i) => label+': '+player.attributes[i]).join(', '))}. Valores ficticios, sin evaluación deportiva real.</desc>${levels}${axes}<polygon points="${player.attributes.map((value,i) => coords(i,value/99*106)).join(' ')}" fill="#50efc6" fill-opacity=".23" stroke="#50efc6" stroke-width="2.5"/>${player.attributes.map((value,i) => {const [x,y] = point(i,value/99*106);return `<circle cx="${x}" cy="${y}" r="3" fill="#b4fff0"/>`;}).join('')}${labels}</svg>`;
}
export function createHeatmapSvg(player, phase = 'all', scope = 'heatmap') {
  if (!['all','ball','off'].includes(phase)) phase = 'all';
  const prefix = id(scope);
  const blobs = player.zones[phase].map(([x,y,r],i) => `<circle cx="${25+x/100*450}" cy="${25+y/100*280}" r="${r*1.65}" fill="url(#${prefix}-spot)" opacity="${i===0?'.95':'.78'}"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350" role="img" aria-labelledby="${prefix}-title ${prefix}-desc"><title id="${prefix}-title">Mapa de calor ilustrativo de ${escape(player.name)}</title><desc id="${prefix}-desc">Simulación de concentración relativa de acciones en un partido ficticio de 90 minutos. Ataque hacia la derecha. ${escape(player.zoneSummary[phase])} No son posiciones GPS ni mediciones reales.</desc><defs><radialGradient id="${prefix}-spot"><stop offset="0" stop-color="#ff593b"/><stop offset=".23" stop-color="#ffd85a"/><stop offset=".49" stop-color="#7ad766"/><stop offset=".73" stop-color="#30b6bd" stop-opacity=".8"/><stop offset="1" stop-color="#276ac1" stop-opacity="0"/></radialGradient><clipPath id="${prefix}-clip"><rect x="25" y="25" width="450" height="280"/></clipPath></defs><rect x="10" y="10" width="480" height="310" rx="5" fill="#102d38"/><g clip-path="url(#${prefix}-clip)">${blobs}</g><g stroke="#d7f7ef" stroke-opacity=".65" stroke-width="1.2" fill="none"><rect x="25" y="25" width="450" height="280"/><path d="M250 25v280"/><circle cx="250" cy="165" r="39"/><path d="M25 91h68v148H25 M475 91h-68v148h68 M25 128h25v74H25 M475 128h-25v74h25"/><circle cx="70" cy="165" r="2" fill="#d7f7ef"/><circle cx="430" cy="165" r="2" fill="#d7f7ef"/></g><text x="25" y="342" font-family="Arial,sans-serif" fill="#b9d5da" font-size="10">${player.kind==='goalkeeper'?'ARCO PROPIO':'CAMPO PROPIO'}</text><text x="475" y="342" text-anchor="end" font-family="Arial,sans-serif" fill="#b9d5da" font-size="10">ATAQUE →</text></svg>`;
}
export function analysisMarkup(player, scope) {
  const attributeLabels = getAttributeLabels(player);
  return `<div class="analysis-grid"><article class="analysis-panel"><div class="analysis-heading"><span>PERFIL DE TALENTO</span><b>${escape(player.code)} / ${escape(player.number)}</b></div><h3>${player.kind==='goalkeeper'?'Atributos de arquero':'Atributos de juego'}</h3>${createRadarSvg(player,scope+'-radar')}<div class="attribute-strip">${attributeLabels.map((label,i) => `<div><span>${escape(label)}</span><strong>${player.attributes[i]}</strong></div>`).join('')}</div><p class="analysis-note">Escala ilustrativa 0–99. Valores ficticios; una ficha real requiere criterio y evaluación documentados.</p></article><article class="analysis-panel"><div class="analysis-heading"><span>ZONAS DE ACCIÓN</span><b>90 MIN · SIMULACIÓN</b></div><h3>Mapa de calor</h3><div class="heat-tabs" role="group" aria-label="Elegir acciones del mapa"><button type="button" data-heat="all" aria-pressed="true">General</button><button type="button" data-heat="ball" aria-pressed="false">Con pelota</button><button type="button" data-heat="off" aria-pressed="false">Sin pelota</button></div><div data-heat-view>${createHeatmapSvg(player,'all',scope+'-heat')}</div><div class="heat-legend"><span>Menor</span><i aria-hidden="true"></i><span>Mayor concentración</span></div><p data-zone-summary>${escape(player.zoneSummary.all)}</p><p class="analysis-note">Fuente: simulación. Concentración relativa de acciones, sin GPS ni datos reales. En producción se indica fuente, período y método.</p></article></div>`;
}
