const menu = document.querySelector('.menu');
const nav = document.querySelector('#navigation');
if (menu && nav) {
 const close = () => {nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menú');};
 menu.addEventListener('click', () => {const open = nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');});
 nav.querySelectorAll('a').forEach(a => a.addEventListener('click',close));
 document.addEventListener('keydown', e => {if(e.key==='Escape'){close();menu.focus();}});
}
document.querySelectorAll('[data-profile]').forEach(link=>link.addEventListener('click',()=>{document.querySelector('#profile').value=link.dataset.profile;}));
const demos = {coach:{mark:'MR',name:'MARCOS RIVERA',role:'ENTRENADOR DE FÚTBOL',slogan:'Experiencia. Metodología.\nUna visión de juego.',image:'assets/coach-hero.webp',alt:'Vista conceptual de la web de un entrenador',href:'demo-coach.html'},agency:{mark:'NORTH',name:'NORTH FOOTBALL',role:'AGENCIA DE REPRESENTACIÓN',slogan:'Talento. Visión.\nUna carrera con dirección.',image:'assets/card-agente.webp',alt:'Vista conceptual de una agencia de representación',href:'demo-agency.html'}};
const tabs=[...document.querySelectorAll('[data-demo]')];
function selectDemo(tab){const d=demos[tab.dataset.demo];tabs.forEach(b=>{b.setAttribute('aria-selected',String(b===tab));b.tabIndex=b===tab?0:-1;});document.querySelector('#demo-panel').setAttribute('aria-labelledby',tab.id);for(const k of ['mark','name','role'])document.querySelector('#preview-'+k).textContent=d[k];const s=document.querySelector('#preview-slogan');s.textContent=d.slogan;s.style.whiteSpace='pre-line';const img=document.querySelector('#preview-image');img.src=d.image;img.alt=d.alt;document.querySelector('#demo-link').href=d.href;}
tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>selectDemo(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=tabs[(index+1)%tabs.length];if(e.key==='ArrowLeft')next=tabs[(index+tabs.length-1)%tabs.length];if(e.key==='Home')next=tabs[0];if(e.key==='End')next=tabs.at(-1);if(next){e.preventDefault();next.focus();selectDemo(next);}});});
const form=document.querySelector('#proposal-form');
form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const values=new FormData(form);const message=['Hola, Agent Authority. Me gustaría recibir una propuesta.','',`Nombre: ${values.get('name').trim()}`,`Perfil: ${values.get('profile')}`,values.get('site')?`Web / LinkedIn: ${values.get('site').trim()}`:'',`Objetivo: ${values.get('goal').trim()}`].filter(Boolean).join('\n');document.querySelector('#message-preview').value=message;document.querySelector('#send-whatsapp').href='https://wa.me/5492226638043?text='+encodeURIComponent(message);const result=document.querySelector('#form-result');result.hidden=false;result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'nearest'});document.querySelector('#send-whatsapp').focus();});
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
